name: Release Gem

on:
  push:
    tags:
      - "v*"

jobs:
  push:
    runs-on: ubuntu-latest
    name: Push gem to RubyGems.org
    container:
      image: debian:latest

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # IMPORTANT: this permission is required for `rake release` to push the release tag

    steps:
      - name: Update git
        run: |
          apt-get update
          apt-get install -y git

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install Ruby dependencies
        run: |
          apt-get update
          apt-get install -y \
            ruby \
            ruby-dev \
            bundler \
            build-essential \
            git \
            libmagickcore-dev \
            autotools-dev \
            autopoint \
            diffutils \
            libtool \
            intltool \
            libpng-dev \
            libexif-dev \
            libtiff5-dev \
            libjpeg-dev \
            libxml2-dev \
            libbz2-dev \
            libpstoedit-dev \
            libfreetype6-dev \
            libpstoedit0c2a \
            libbz2-1.0 \
            libgd3 \
            libffi-dev \
            pkg-config \
            curl \
            wget

      - name: Build and install Autotrace from source
        # Following the same build process as in the Dockerfile
        run: |
          git clone https://github.com/autotrace/autotrace.git
          cd autotrace
          ./autogen.sh
          ./configure --prefix=/usr
          make
          make install
          ldconfig
          cd ..

          # Verify autotrace is installed
          autotrace --version

          # Check for required libraries
          echo "Checking for required libraries:"
          ldconfig -p | grep "libautotrace"

      - name: Install Dependencies
        run: |
          # Install the same FFI version as in the Dockerfile
          gem install ffi -v "~> 1.17.1"
          # Install bundler and project dependencies
          bundle install

      # Manual implementation of the steps from rubygems/release-gem action
      - name: Set git configuration
        run: |
          # Attribute commits to the last committer on HEAD
          git config --global --add safe.directory "$(pwd)"
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"
          git config --global user.name "$(git log -1 --pretty=format:'%an')"
          git remote set-url origin "https://x-access-token:${{ github.token }}@github.com/$GITHUB_REPOSITORY"
        shell: bash

      - name: Configure trusted publishing credentials
        uses: rubygems/configure-rubygems-credentials@v1.0.0

      - name: Run release rake task
        run: bundle exec rake release
        shell: bash
        env:
          RUBYOPT: "-r./rubygems_attestation_patch.rb"

      - name: Wait for release to propagate
        run: |
          # First install the gem to get access to rubygems-await
          gem install rubygems-await
          # Then wait for the package to be available
          gem exec rubygems-await pkg/*.gem
        shell: bash
