name: Release Gem

on:
  push:
    tags:
      - "v*"

jobs:
  push:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # IMPORTANT: this permission is required for `rake release` to push the release tag

    steps:
      # Set up repository and Ruby
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for version determination

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true

      - name: Install libffi
        run: sudo apt-get update && sudo apt-get install -y libffi-dev

      # Build and publish gem
      - name: Release gem
        uses: rubygems/release-gem@v1
